### ISSUE TITLE
游戏启动时提示应用错误

### ISSUE THREAD

**Issue by Snakebinp** [clinlx/CN_GreenLumaGUI#1]

**Comment by clinlx** [comment]
所有能正常解锁，但是不能正常启动游戏的问题，或者不能联网，基本都是GreenLuma本身的局限。
比如报错：Application load error 6:0000065432 什么的。
我只做一个GUI啊。所以说这个不是我的写出来的BUG。
GreenLuma不支持被DRM保护的游戏，也不支持D加密的游戏，更不支持游戏自己联网验证账号的游戏。
这个国外大神的项目可以解决DRM问题：https://github.com/atom0s/Steamless
