### ISSUE TITLE
好像解锁不了DLC

### ISSUE THREAD

**Issue by oohu123** [clinlx/CN_GreenLumaGUI#11]
比如喵斯快跑这个游戏，按道理应该能解锁DLC的啊，结果无法解锁DLC，账号显示我有dlc了，但是上游戏没有dlc啊

**Comment by oohu123** [comment]
测试了一下，好像是GreenLuma本来就没有办法在只有本体的情况下解锁DLC，但是如果号上本体+DLC，就可以把本体+DLC入库到别的号上，如果号里只有本体没有DLC，就无法入库DLC，只有本体。
测试软件配合CreamInstaller一起使用，无冲突，我觉得作者可以尝试一下这个更新
GreenLuma+CreamInstaller结合，CreamInstaller负责DLC的部分

**Comment by oohu123** [comment]
测试了一下
如果号上本体+DLC就可以把本体+DLC入库到别的号上使用。
如果号里只有本体没有DLC，入库后，虽然显示你有DLC，但是打开游戏后还是没有DLC的内容。
测试CN_GreenLumaGUI配合CreamInstaller一起使用，无冲突
可以入库解锁DLC，CreamInstaller是解锁DLC的专用工具。

**Comment by clinlx** [comment]
只有少部分游戏可以直接解锁DLC。
很多DLC都要你下载文件的，你本地没有文件，即使账号显示有，实际还是运行不了的。
所以借号下载可以解决问题。

**Comment by oohu123** [comment]
> 只有少部分游戏可以直接解锁DLC .很多扩展票都要你下载文件的,你本地没有文件,即使账号显示有,实际还是运行不了的。所以借号下载可以解决问题。

可能GreenLuma的解锁DLC功能并不完整，CreamInstaller可以解锁绝大多数的游戏DLC，但是解锁的前提是DLC已经下载到本地了，比如喵斯快跑这个游戏，你并没有DLC，你下载游戏本体，DLC也会一起在本体里面，这个时候就可以用CreamInstaller解锁，但是用GreenLuma解锁不了。
