### ISSUE TITLE
steam无法启动：显示错误消息 'the system cannot execute specified program

### ISSUE THREAD

**Issue by ALI2580** [clinlx/CN_GreenLumaGUI#12]
## 描述

当我尝试使用该软件启动Steam时，即使在兼容模式或管理员模式下，它也无法启动。点击关闭Steam是正常的，但无法启动Steam。尝试了不同的启动模式，但始终显示错误消息“the system cannot execute specified program”。

## 重现步骤

1. 打开CN_GreenLumaGUI，启动Steam。
2. 尝试以兼容模式或管理员模式运行。
3. 在非兼容模式下观察到错误消息：“the system cannot execute specified program”。

## 预期行为

CN_GreenLumaGUI启动Steam应正常启动，无论是在常规模式、兼容模式还是管理员模式下。

## 截图

![问题截图](https://mark-down-images.oss-cn-beijing.aliyuncs.com/myimg/image-20230810001825554.png)

## 系统信息

- 操作系统: Windows 11 22H2
- Steam版本:  1690583737
- 是否已尝试重装CN_GreenLumaGUI：是

请帮助解决这个问题，谢谢！

**Comment by clinlx** [comment]
你好，我很早在日志里发现了多起这种情况。
但是现在还没修复是因为难以复现，我测试了几台Win7、Win10、Win11均正常。
因此无法找到原因，但是我能猜测原因：
一般情况下出现这种情况，要么是运行库缺失，要么就是被Windows安全中心给拦截了。(DLL注入是病毒常用的技术，被拦截也很正常)。
一般我会让用户在使用前安装其他安全软件(比如火绒)来让Windows自带的安全中心失效。

你先检查一下是不是这种情况。
如果不行，软件会在运行一次以后，会生成原版GreenLuma的文件，用于启动Steam的注入器是“C:\tmp\exewim2oav.addy.vlz\DLLInjector\DLLInjector.exe”，但是关闭软件的时候会清理，可以在窗口未关闭的情况下试着手动运行一下，看看会报什么错。

如果错误是因为原版GreenLuma导致的，那我并无法修改源代码，不保证能修好，所以只能尽最大努力帮你找解决办法。

**Comment by ALI2580** [comment]
非常好，爱来自中国，我把C:\tmp\添加到windows安全中心的白名单中就可以正常使用了
