### ISSUE TITLE
steam更新了，好像不能用了。

### ISSUE THREAD

**Issue by wangzhilin777** [clinlx/CN_GreenLumaGUI#13]
我用GreenLuma_2023_1.4.5-Steam006最新的可以。应该需要更新内置的dll文件了。可以考虑加一个支持自定义引入，像greenlumaMgr一样。
请问：有没有考虑手动支持批量DLC加入呢？有较多DLC的游戏加起来有点老火。

**Comment by clinlx** [comment]
内置的现在就是GreenLuma_2023_1.4.5啊。
而且我直到现在试了都能正常使用，你应该只是暂时卡了。可能早上起来就正常了也说不定。

批量DLC加入功能，你的描述感觉说得不是很具体。既然是手动，那怎么批量，写在文本文件里，一行一个吗？
我觉得连上网，用游戏右边的绿色刷新按钮获取DLC，目前已经够用了。
