### ISSUE TITLE
在一个游戏中无法解锁超过11dlc

### ISSUE THREAD

**Issue by Bladerunnerss** [clinlx/CN_GreenLumaGUI#14]
在一个游戏中无法解锁超过11dlc
测试游戏莱莎的炼金工房，共有24个dlc，解锁器中添加24个dlc 实测最多可同时解锁11个，剩下的dlc要在解锁器中取消已经勾选的dlc才行

**Comment by clinlx** [comment]
我测试了一下，不是DLc不能超过11个。
而是所有解锁项目总数不能超过24个，否则后面的无论是游戏还是DLC都会失效。
目前不知道这个状况是什么时候出现的。（可能是Steam更新了?）

**Comment by clinlx** [comment]
更新v1.2.10即可
