### ISSUE TITLE
win11 系统运行没反应 

### ISSUE THREAD

**Issue by Sir-H** [clinlx/CN_GreenLumaGUI#15]
运行没反应，进程管理器 一闪而过。看了下C盘下没有TMP文件夹。
运行环境已经安装。杀毒软件是火绒已经关闭。
![Snipaste_2023-11-03_22-22-23](https://github.com/clinlx/CN_GreenLumaGUI/assets/27133701/49ac926e-e0ce-435e-8dec-85ed77c942c0)

**Comment by clinlx** [comment]
我复现不了。
1、确保软件在一个合适的目录下运行。（比如：不要在压缩包里运行，还有可以复制exe文件到D:\等一定没有权限问题的目录下。）
2、有可能只是进程卡住了。你先重启一下电脑试试。
3、如果直接重启电脑无效，然后尝试安装一下https://aka.ms/vs/17/release/vc_redist.x86.exe，进行所有VC++运行库的修复，然后重启。
进程关闭了，但是没有创建Tmp文件夹，这从代码上看，理论上是不可能发生的。
只有可能是电脑环境问题。
无论如何都无法解决的话，那只能去使用其他同类软件了（或者重新安装系统）。
这是我的Main函数：（除非故意带参数启动，或者已经运行了一个同名的软件，否则就一定会创建tmp目录）
![Uploading {CA29E59E-B0C1-415b-93F8-9CE0676F8AA1}.png…]()
在代码上无法修复这个问题。

**Comment by Sir-H** [comment]
感谢回复。通过系统日志，判断是scoop安装的dotnet-sdk库存在冲突。卸载了就可以正常打开了。
![Snipaste_2023-11-04_15-26-55](https://github.com/clinlx/CN_GreenLumaGUI/assets/27133701/27ecf111-4f57-42df-b568-bbeb50386474)
