### ISSUE TITLE
可以弄个清单密钥功能

### ISSUE THREAD

**Issue by Temlpe** [clinlx/CN_GreenLumaGUI#17]
可以弄个清单密钥功能，让用户自己输入，或者弄个云让用户自己上传也行
我测试弄完清单密钥，再用你的软件解锁，可以下载和游玩的
原理也很简单，如果作者不太了解跟我告诉我

**Comment by clinlx** [comment]
听着好像很麻烦。
但是如果只是文件替换进去还是没问题的。
