### ISSUE TITLE
关于最新版V1.2.15.20103解锁失效的问题

### ISSUE THREAD

**Issue by segadcss** [clinlx/CN_GreenLumaGUI#19]
使用蓝奏云的V1.2.15.20103版本解锁不生效，用你发布的V1.2.11.28415可以使用，我不知道是我使用的问题还是版本的问题。

**Comment by yaglanlan** [comment]
你的Steam是最新版吗？

**Comment by clinlx** [comment]
如果V1.2.11.28415可以用那就先用这个版本。因为这几个版本的更新没有真正更新任何实质内容，只是更新了DLL文件的版本。

**Comment by segadcss** [comment]
是最新版的steam,那就先用老版了，新版你也测试一下

**Comment by ChangKaz** [comment]
除V1.2.11.28415外不可用，steam是families beta版本

**Comment by clinlx** [comment]
每个版本我都是测试过的，而且自己也一直用最新版本。应该是没问题的。
这几个版本我更新了注入器和DLL文件，我猜可能是旧的临时文件卡占用了，所以临时没更新成功。
如果不嫌弃麻烦的话，你可以重启电脑解除占用，试着删除C:\tmp\exewim2oav.addy.vlz下面的DLLInjector文件夹后再用新版本试试。

**Comment by segadcss** [comment]
按以上方法新版也可以解锁
