### ISSUE TITLE
大佬，用这个工具解锁好了，为什么steam里没有入库呢，需要其他的东西吗？

### ISSUE THREAD

**Issue by 2385347602** [clinlx/CN_GreenLumaGUI#2]

**Comment by clinlx** [comment]
"解锁"这个功能的意思是，把你已经安装好的游戏那个“开始游戏”的按钮给解锁了。
这样可以达到，借别人号下载以后自己玩，或者和别人同时游玩共享游戏的目的。
你的游戏库里面该有什么就有什么，并不会把你没有下载的游戏入库。

**Comment by 2385347602** [comment]
明白了，谢谢大佬，联网的游戏也可以玩吗

**Comment by 2385347602** [comment]
CN_GreenLumaGUI

**Comment by 2385347602** [comment]
明白了，谢谢大佬，联网的游戏也可以玩吗

**Comment by clinlx** [comment]
基本上不可以。
但是如果有人共享这个游戏给你，你就可以联网玩大多数游戏（普通的Steam共享游戏，正常情况下同时只能有一个人玩游戏。主机上线，被共享者就会掉线。所以使用解锁器的意义是，可以让两个人一起开游戏联机。）。但是仍然有一部分无法玩。

**Comment by clinlx** [comment]
所以如果关系比较好，相互信任，可以考虑多人合买一份游戏玩。
比如买一个老头环原价300元，平均每人只要花50，一个寝室6人同乐（因为Steam最多可以给5个人共享，所以是6人）。
