### ISSUE TITLE
希望能增加，可选自动添加Depots的ID到AppList

### ISSUE THREAD

**Issue by wangzhilin777** [clinlx/CN_GreenLumaGUI#20]
大佬你好，因为清单密钥工具导入清单和密钥后，如果想要steam自动下载，需要识别到Depots的ID才能开始自动下载。所以希望能添加一下这个功能。
![image](https://github.com/clinlx/CN_GreenLumaGUI/assets/75417416/1e9a9051-e2ff-4720-8b11-2ff618fd8432)

**Comment by clinlx** [comment]
从线上自动获取DepotsID有点难度，因为SteamDB是不能乱用爬虫爬数据的，Steam官方的Api我也没翻到查询DepotsID的地方。
最合理的方式我觉得其实是从本地清单文件里面读DepotsID（因为你已经提前把要解锁的清单合并进去了）我找时间看看能不能做。

其实我的软件规划里面，有一大堆和清单相关的功能。但是目前还挺遥远，真的抽不出时间精力去做了。

**Comment by Jiangdonganxia** [comment]
> 我看了一下清单文件，好像内容有点多，而且根本无法区分这个清单属于哪个游戏。 而且我也不知道Steam获取DepotsId的Api，这个功能短期内应该没法做了。

大佬，你看能不能通过这个插件获取，然后导入进来我们的软件
https://github.com/Sak32009/GetDataFromSteam-SteamDB

**Comment by Jiangdonganxia** [comment]
> 我看了一下清单文件，好像内容有点多，而且根本无法区分这个清单属于哪个游戏。 而且我也不知道Steam获取DepotsId的Api，这个功能短期内应该没法做了。

让用户自己用这个插件获取ini

**Comment by clinlx** [comment]
我目前选择还是先使用本地的数据，先扫描已经存在的清单，这样至少不用一个个输入了。
最新版本更新了一个比较原始的清单功能，可以简化操作。
