### ISSUE TITLE
希望增加 不同设备的解锁列表同步 功能

### ISSUE THREAD

**Issue by ypq123456789** [clinlx/CN_GreenLumaGUI#23]
如图所示，如果不支持的话，麻烦开发者说一下不同设备的解锁列表同步的信息的存储位置可以吗？否则有的游戏有很多dlc，重新在另一台设备上解锁太吐血了

**Comment by clinlx** [comment]
C:\tmp\exewim2oav.addy.vlz\unlocklist.json
