### ISSUE TITLE
请问怎么使用啊

### ISSUE THREAD

**Issue by cahkcs** [clinlx/CN_GreenLumaGUI#24]
他只是UI还是真的有功能，为什么我选择完游戏，点击启动steam什么都没有

**Comment by clinlx** [comment]
当然是有功能的。
但是“什么都没有”是什么意思，是指Steam打不开吗？没有任何弹窗吗？能详细说说吗。

**Comment by cahkcs** [comment]
> 当然是有功能的。
> 但是“什么都没有”是什么意思，是指Steam打不开吗？没有任何弹窗吗？能详细说说吗。

就是我选择完游戏了，然后点启动steam，然后启动完进入steam里面依然没有我选择的游戏

**Comment by clinlx** [comment]
兄弟，我在“常见问题”里面解释过这个事情了。
我这不是入库工具，只是个解锁工具。所以它本来就不能让你库里多出你为拥有的游戏。只能让你没有权限游玩、但是本地已经下载的游戏能强行游玩。

**Comment by cahkcs** [comment]
> 兄弟，我在“常见问题”里面解释过这个事情了。
> 我这不是入库工具，只是个解锁工具。所以它本来就不能让你库里多出你为拥有的游戏。只能让你没有权限游玩、但是本地已经下载的游戏能强行游玩。

好的哥，是我眼瞎了
