### ISSUE TITLE
升到net8.0吧. 另外下载时chrome报不安全不让下是什么情况?

### ISSUE THREAD

**Issue by cuteribs** [clinlx/CN_GreenLumaGUI#25]

**Comment by clinlx** [comment]
它现在能跑，所以我暂时不想动它。而且.net8.0的新特性对这个项目来说并不必要。
用这个软件的有不少是小白，并不是程序员，电脑没有安装.net8的runtime或者sdk。如果我升级.net8.0，他们全部都要重新安装新的runtime的，很麻烦的。

报毒是正常的，因为GreenLuma，本身就是一个注入steam进程的dll文件。在安全软件看来，一个含有注入代码的程序本来就是危险软件。很多病毒就是用这种手段隐藏的。尽管使用这种手段的不一定是病毒。所以被认为不安全是正常的。

**Comment by cuteribs** [comment]
回复很快, 感谢 :)

我只装了6和8, 7不是lts所以无视了. 😆
