### ISSUE TITLE
软件能打开steam，但解锁游戏失败

### ISSUE THREAD

**Issue by ZGC4846** [clinlx/CN_GreenLumaGUI#26]
我第一次用软件打开steam可以解锁成功，但是点关闭steam之后再在软件里点启动steam就再也没解锁成功过，游戏显示需要购买。之前还能通过重启电脑重新解锁，现在重启也无法解锁了。请问这种情况我该怎么解决呢？
![屏幕截图 2024-08-08 122742](https://github.com/user-attachments/assets/dca08be8-f079-4e8f-b349-36c9fd16dcbb)
![屏幕截图 2024-08-08 122721](https://github.com/user-attachments/assets/b392bc53-0ed5-462b-8ad0-b5b4acb4bb0f)

**Comment by clinlx** [comment]
现在无法解锁，可能是Steam更新导致的，稍后等我更新软件后，你重新试试。

之前重启后能解决，应该是因为C:\tmp\exewim2oav.addy.vlz\DLLInjector的文件夹下的某个文件被某个软件占用了（可能是退出steam不干净）尝试全删除就能找到是哪一个进程占用了文件。（删除这些临时文件并不影响）
像是Microsoft PowerToys这样的软件也能直接找到文件被谁占用了。找到后可以自己试试关闭这个进程，或者发给我看看是什么情况。

**Comment by ZGC4846** [comment]
> 现在无法解锁，可能是Steam更新导致的，稍后等我更新软件后，你重新试试。
> 
> 之前重启后能解决，应该是因为C:\tmp\exewim2oav.addy.vlz\DLLInjector的文件夹下的某个文件被某个软件占用了（可能是退出steam不干净）尝试全删除就能找到是哪一个进程占用了文件。（删除这些临时文件并不影响） 像是Microsoft PowerToys这样的软件也能直接找到文件被谁占用了。找到后可以自己试试关闭这个进程，或者发给我看看是什么情况。

感谢回复，我刚刚在另一台电脑上使用了软件，老情况开机后首次进入软件开启steam能正常解锁，但是关闭steam后就无法再次解锁了，我在开着软件的时候去删除文件，显示是log.txt和logerr.txt这两个日志文件在被占用，关闭steam后这俩文件也可以被删除了。

**Comment by clinlx** [comment]
软件已更新。

理论上来说，软件第几次启动其实对结果没有任何影响。删除了那些文件就更加不可能有影响了。我觉得唯一的可能就是Steam进程未完全退出。

这种不稳定的事情一直有人报告，我也找不到原因，所以只能在常见问题里面写让人重启了。

我自己也偶尔遇到一些游戏比如老头环不能解锁，而此刻其他游戏可以的情况。这应该是这个DLL的问题，不是我这个UI的问题，如果是这种情况我就解决不了。
