### ISSUE TITLE
希望增加 本地清单入库 和 成就解锁 功能

### ISSUE THREAD

**Issue by fylsdy** [clinlx/CN_GreenLumaGUI#29]
就像steamtools一样

**Comment by clinlx** [comment]
做不了，这些功能太复杂了

**Comment by fylsdy** [comment]
可以参考下这个 
steam game key 写入vdf教程（GL 手动 unlock 清单教程）
https://www.bilibili.com/video/BV164p9eeEPa/?spm_id_from=333.880.my_history.page.click

**Comment by liucyin** [comment]
> 可以参考下这个 steam game key 写入vdf教程（GL 手动 unlock 清单教程） https://www.bilibili.com/video/BV164p9eeEPa/?spm_id_from=333.880.my_history.page.click

视频无了

**Comment by clinlx** [comment]
我还没来得及看这个视频

**Comment by fylsdy** [comment]
找到了纯手动解锁方式的帖子
https://caigames.cn/thread-1767.htm

**Comment by clinlx** [comment]
暂时 还没做导入清单的功能，也没做成就解锁。但是参考了这个手动解锁的帖子，我先新增了一个页面用来选择本地已经导入的清单，然后便于按照它们的Depot解锁。

**Comment by clinlx** [comment]
最新版支持了清单和密钥文件的导出和导入，你看看还有什么要补充的吗。

至于成就，实在是过于复杂，而且不是软件的重点，因此不列入计划中。你可以直接用SAM（SteamAchievementManager）
