### ISSUE TITLE
老哥软件下完后无法在软件内启动steam，用steamtools打开steam软件也无法起作用

### ISSUE THREAD

**Issue by wd95513349** [clinlx/CN_GreenLumaGUI#3]
该如何操作呢？

**Comment by clinlx** [comment]
有什么明显的弹窗吗？
下载最新版，然后试试启动一下。
然后把下面三个文件发到我邮箱clinlx@foxmail.com，我试试能不能修好
C:\tmp\exewim2oav.addy.vlz\log0.txt
C:\tmp\exewim2oav.addy.vlz\log.txt
C:\tmp\exewim2oav.addy.vlz\logerr.txt

**Comment by Tacrine** [comment]
我也是，最新版，启动不了steam，其他的都已经设置好了

**Comment by clinlx** [comment]
> ，

我这是在请求你们帮忙呀。所以你们倒是把日志发我呀。不发我， 肯定是找不到原因的，我也修不好。

**Comment by Tacrine** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by wd95513349** [comment]
***@***.******@***.***
更新到最新版，点击启动steam一直卡进度条不期待，且没有txt文件
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年7月14日 14:47
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [clinlx/CN_GreenLumaGUI] 老哥软件下完后无法在软件内启动steam，用steamtools打开steam软件也无法起作用 (Issue #3)


有什么明显的弹窗吗？
下载最新版，然后试试启动一下。
***@***.******@***.***>，我试试能不能修好
C:\tmp\exewim2oav.addy.vlz\log0.txt
C:\tmp\exewim2oav.addy.vlz\log.txt
C:\tmp\exewim2oav.addy.vlz\logerr.txt

―

**Comment by clinlx** [comment]
你们几个再试试看，会不会报什么错。
我认识的人运行都正常，找不到测试样本啊。

**Comment by wd95513349** [comment]
没问题了能正常启动steam了
