### ISSUE TITLE
DLC获取不全

### ISSUE THREAD

**Issue by Remtobbb** [clinlx/CN_GreenLumaGUI#33]
![1728624497563](https://github.com/user-attachments/assets/b48a359b-8971-4f7f-bf72-c824e7bdce62)
![1728624517335](https://github.com/user-attachments/assets/d873d115-c680-4640-81f5-98921e88f86a)
只能获取8个 后面2个是自己加的
这个能解决吗

**Comment by clinlx** [comment]
我看了一下，好像是因为这俩个DLC并未在Steam商店页面发布。（或者是被隐藏了）

这个功能的数据来源并不是SteamDB，而且是Steam官方商店页面。因为SteamDB是禁爬虫的。
