### ISSUE TITLE
not adding

### ISSUE THREAD

**Issue by lucy2000** [clinlx/CN_GreenLumaGUI#37]
why are games not adding to my library do i need to set files to steam folder or

**Comment by clinlx** [comment]
This software is just a GUI for GreenLuma, and it offers the same functionality. Moreover, it's not designed to display games in your library that you don't own. It's generally used for families sharing a multiplayer game library, where the games are already supposed to appear in your library. If you want to add games to your library and have the ability to download them at any time, it's quite complex: you would need to manually add Manifest files, merge the keys of the Manifest files into the Steam directory, and trigger the game installation manually via the command line using steam://install/appid. In short, if you haven't done this before, it's safe to say that it's practically not feasible without prior experience.
