### ISSUE TITLE
你好，请问这个软件的安装路径在哪里？

### ISSUE THREAD

**Issue by xulei-best** [clinlx/CN_GreenLumaGUI#4]

**Comment by clinlx** [comment]
没有安装路径。这个软件只有一个文件。
但是有数据文件夹路径，数据文件夹路径可以在软件的“设置”选项里面使用“清空软件数据”按钮打开。
软件本体+数据文件夹，就是全部了，没有其他文件了。

如果你只是想卸载.net的运行时（不推荐，因为有其他很多软件都需要.net运行时），那可以看看微软这篇文档：learn.microsoft.com/zh-cn/dotnet/core/install/remove-runtime-sdk-versions
