### ISSUE TITLE
Windows7系统报错“DLLInjector.exe 不是有效的win32应用程序”

### ISSUE THREAD

**Issue by xiao-zheng233** [clinlx/CN_GreenLumaGUI#6]
使用windows7 x64普通权限、管理员权限下打开软件，选择游戏后单击启动，即报此错。
去查看了一下DLLInjector.exe确实存在PE头，肯定是base64解码完了的。

运行环境：
- .NET Framework 4.7.2，
- .NET Framework 4.8 + SDK，
- Microsoft Windows Desktop Runtime 6.0.5 x64，
- Microsoft Windows Desktop Runtime 7.0.9 x86  

使用的系统：'Y-OS Win7 SP1 x86&x64 纯净旗舰版v202101 ，64位驱动总裁版， YOS_W7X64SC_202101.esd'

错误如下图所示：
![image](https://github.com/clinlx/CN_GreenLumaGUI/assets/93850579/48b78e55-a33a-4490-9d2d-a84ebd78d3b3)

**Comment by clinlx** [comment]
感谢反馈。但是我能测试的环境很有限，我没法复现，所以我没找到原因。

**Comment by clinlx** [comment]
我用32位和64位的虚拟机查过了。
是原Dll注入器本身只支持Win10及以上系统导致的。
我用c++重新写了一个注入器就解决了。下个版本更新。（但是这会牺牲隐身性能）

还有，steam明年(2024)就不支持win7系统了，早日升级系统吧。
