### ISSUE TITLE
请问能否手动操作接触128解锁数量限制

### ISSUE THREAD

**Issue by Janyskm** [clinlx/CN_GreenLumaGUI#7]
因为部分游戏的DLC数量非常多, 比如怪物猎人 多达244个DLC. 
有办法解决 128的限制吗?

**Comment by clinlx** [comment]
我只能把它提升到137个上限，下个版本我给它改成149吧。

因为Greenluma并不开源，最多只能解锁149个是作者写在程序里的硬限制，原因未知，应该作者是遇到了什么BUG，再多我也没办法了。。。

**Comment by Janyskm** [comment]
ok 谢谢
