### ISSUE TITLE
部分游戏搜不到,steam接口限制？

### ISSUE THREAD

**Issue by wangzhilin777** [clinlx/CN_GreenLumaGUI#8]
比如mirror，我分别用三个关键词都搜不到：Mirror 、KAGAMI WORKS 、Paradise Project，名称、开发商、发行商，都能搜到部分其它相关信息，就是没有Mirror，不知道什么情况。steamdb能搜到，我看土区也能正常购买。

**Comment by wangzhilin777** [comment]
我使用Greenluma Manager 英文版本的，测试可以搜到Mirror

**Comment by wangzhilin777** [comment]
仅限成人的，好像都搜不到，应该是接口限制

**Comment by clinlx** [comment]
正常现象。因为这个接口是从Steam商店逆向的。。。这也是因为SteamDB它禁止爬虫，所以选择了从商店直接搜。
所以只要在网页版商店里面搜不到的，这里面也搜不到。(除非Steam认为你在外区)

搜索这个功能只是为了降低使用成本，最后还是要和“手动添加游戏”的功能互补。
（但是功能性的更新目前没时间做，需要的话手动改C:\tmp\exewim2oav.addy.vlz\unlocklist.json文件内容就好。甚至其他人写一个外部修改json文件的工具也是很简单的。）

**Comment by wangzhilin777** [comment]
> 正常现象。因为这个接口是从Steam商店逆向的。。。这也是因为SteamDB它禁止爬虫，所以选择了从商店直接搜。 所以只要在网页版商店里面搜不到的，这里面也搜不到。(除非Steam认为你在外区)
> 
> 搜索这个功能只是为了降低使用成本，最后还是要和“手动添加游戏”的功能互补。 （但是功能性的更新目前没时间做，需要的话手动改C:\tmp\exewim2oav.addy.vlz\unlocklist.json文件内容就好。甚至其他人写一个外部修改json文件的工具也是很简单的。）

嗯嗯，应该是steam识别为国区了，毕竟Greenluma Manager还得挂梯子，这个不用。
谢谢解答疑问！

**Comment by clinlx** [comment]
“手动添加”功能已更新
